In [1]:
import numpy as np

In [2]:
x = np.array(list(range(100))).reshape((10, 10))

In [3]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [4]:
m = np.ma.MaskedArray(x)

In [5]:
m

masked_array(data =
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]],
             mask =
 False,
       fill_value = 999999)

In [7]:
n1 = np.ma.masked_where(x % 2 == 0, x)

In [9]:
n2 = np.ma.masked_where(x % 3 == 0, x)

In [16]:
m.mask = n1.mask | n2.mask

In [17]:
m

masked_array(data =
 [[-- 1 -- -- -- 5 -- 7 -- --]
 [-- 11 -- 13 -- -- -- 17 -- 19]
 [-- -- -- 23 -- 25 -- -- -- 29]
 [-- 31 -- -- -- 35 -- 37 -- --]
 [-- 41 -- 43 -- -- -- 47 -- 49]
 [-- -- -- 53 -- 55 -- -- -- 59]
 [-- 61 -- -- -- 65 -- 67 -- --]
 [-- 71 -- 73 -- -- -- 77 -- 79]
 [-- -- -- 83 -- 85 -- -- -- 89]
 [-- 91 -- -- -- 95 -- 97 -- --]],
             mask =
 [[ True False  True  True  True False  True False  True  True]
 [ True False  True False  True  True  True False  True False]
 [ True  True  True False  True False  True  True  True False]
 [ True False  True  True  True False  True False  True  True]
 [ True False  True False  True  True  True False  True False]
 [ True  True  True False  True False  True  True  True False]
 [ True False  True  True  True False  True False  True  True]
 [ True False  True False  True  True  True False  True False]
 [ True  True  True False  True False  True  True  True False]
 [ True False  True  True  True False  True False  True  True]

In [18]:
t = np.array(list(range(125))).reshape((5, 5, 5))

In [21]:
t[0, :, :]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [26]:
mask_3d = np.broadcast_to(t[0, :, :] % 3 == 0, t.shape)

In [31]:
tm = np.ma.masked_where(mask_3d, t)

In [34]:
tm[:, 1, :]

masked_array(data =
 [[5 -- 7 8 --]
 [30 -- 32 33 --]
 [55 -- 57 58 --]
 [80 -- 82 83 --]
 [105 -- 107 108 --]],
             mask =
 [[False  True False False  True]
 [False  True False False  True]
 [False  True False False  True]
 [False  True False False  True]
 [False  True False False  True]],
       fill_value = 999999)